# Generated by Django 3.1.1 on 2020-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_pub_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_vote',
            field=models.IntegerField(default=0),
        ),
    ]
